services:
  
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=develop
      - MONGO_INITDB_ROOT_PASSWORD=develop
  
  mongo_express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=develop
      - ME_CONFIG_MONGODB_ADMINPASSWORD=develop
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
